// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqmcrxkbwelpepodbyqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxbWNyeGtid2VscGVwb2RieXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NzQ3MjMsImV4cCI6MjA2MzA1MDcyM30.hY7QEzTPWe-YjxGUz6n3GiDK_pb33v0Jvx9mCAGypqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);